### ISSUE TITLE
Asking for best_ckpt

### ISSUE THREAD

**Issue by zgdjcls** [tonyzhaozh/act#20]
Hi, I followed your instructions to create 50 simulated examples for the **insertion** task and used the default settings to train the model. However, the evaluation performance was bad, I trained 700 epochs and the eval success rate was only 10%. As you mentioned it should be around 50% for this task. 
**Could you please upload your best_ckpt for this task or the training details to achieve such a success rate?**
Thank you for your sharing.

**Update**: After training for 2000 epochs, it achieved 50% success rate. Although the losses don't show much difference, I guess that's crucial to this task. Sorry for any inconvenience.

**Comment by gauravpradeep** [comment]
@zgdjcls hi, were you able to get the best_ckpt from the authors
