### ISSUE TITLE
AttributeError: 'RealEnv' object has no attribute '_physics'

### ISSUE THREAD

**Issue by onePnot1** [tonyzhaozh/act#7]
Hi, 

Thanks for the excellent work!

I collected some demonstrations with ALOHA (real platform) and run the `act/imitate_episodes.py` program. When I evaluated the trained checkpoint with args `--eval --onscreen_render`, I got the error `AttributeError: 'RealEnv' object has no attribute '_physics'`.

Can you give me some suggestions about how to fix it?

**Comment by tonyzhaozh** [comment]
You should not include the --onscreen_render file! That is for sim envs.

Thanks,
Tony
