### ISSUE TITLE
which coordinate system are the actions involved in training?

### ISSUE THREAD

**Issue by 123zhen123** [tonyzhaozh/act#8]
Hi, Thanks for great paper. 

I encountered a problem: 
which coordinate system are the "actions" (rotation and position) involved in training? Is it in the camera coordinate system or the robot arm base coordinate system? If it is under arm base and there are two robotic arms, which one should prevail? Similarly, if it is a camera coordinate system, which one should prevail?

**Comment by tonyzhaozh** [comment]
Hi, we are doing joint position control here. Simply 2x (6dof arm + 1dof gripper) = 14dim, directly predicted by the neural network.
